### ISSUE TITLE
server side

### ISSUE THREAD

**Issue by armanlearn** [DavyJonesLocker/client_side_validations-simple_form#60]
hi
if i use client_side_validations-simple_form the server side validation still work ?
i mean is it possible to use double check validation in server side ?

tanks

**Comment by tagliala** [comment]
Hi, maybe I didn't get this question properly

If you are using the simple form plugin and client side validation, you should use this gem too.

Server side validations are always ran, CSV only brings (most of) these validations on the client side

**Comment by armanlearn** [comment]
Hi again and Tanks for your answer

No I don't mean that. I want to know if I use "client_side_validations-simple_form" rails framework's native validation still work. I mean if "client_side_validations-simple_form" work hybrid and my app validate form twice . like
1- first "client_side_validations-simple_form" validates my form 
2- rails server side validation double check and recheck form value.

I heard that client side validation is not safe method and it is better to validate form in server side. according client site validation seems have better user experience. i want to have both client side and server side validation in same time. in simple work my question is if possible that : "client_side_validations-simple_form" and rails server side validation works in same times.

**Comment by tagliala** [comment]
> 1- first "client_side_validations-simple_form" validates my form 
2- rails server side validation double check and recheck form value.

This is exactly what the gem is designed for: it checks fields on the client side to help the user (eg: tell user that password requires N chars on the fly, do not send the form to the server and then come back with a "password too short" message) **and** rails keeps checking the fields on the server side

> I heard that client side validation is not safe method and it is better to validate form in server side. 

This is absolutely right, you should in any case rely on user input

> i want to have both client side and server side validation in same time

You will have both. Since CSV works with JavaScript, you can try to disable JS and submit the form, so you will see that server side validations are still working

Hope it helps

**Comment by tagliala** [comment]
Closing here, hope it helps
