### ISSUE TITLE
uniqueness validation not working rails 4

### ISSUE THREAD

**Issue by luis77** [DavyJonesLocker/client_side_validations-simple_form#61]
I am using this gem and all works fine but the validation client with uniqueness in the model don't work, I don't know if I missed something. In the model  
```
class Category < ActiveRecord::Base
	has_many :has_categories
	has_many :articles, through: :has_categories
	validates :name, presence: true, uniqueness: true, length: { minimum: 2 }  

end
```

my form:
```
<%= form_for(@category, validate: true) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name  %>

  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.color_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

```

**Comment by tagliala** [comment]
Hi, you didn't provide enough data to debug this issue.

Also, this is not the right repo to report this kind of issues.

Please check  [Submitting a new issue](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue) and [Security](https://github.com/DavyJonesLocker/client_side_validations#security)

Please also keep in mind that the uniqueness validator is not enabled by default because of security issues (so you need to change your initializer) and doesn't work with some adapters #636
