### ISSUE TITLE
Validations on select input are not working

### ISSUE THREAD

**Issue by mahendhar9** [DavyJonesLocker/client_side_validations-simple_form#63]
Hello. Thanks for the great gem.
I have a country select input with `include_blank: true`. In my model, I have `validates :country, presence: true, allow_blank: false`
But client side validations are being skipped for this select input.
Am I missing something?

**Comment by tagliala** [comment]
Hi,

thanks for reporting this.

Unfortunately I cannot leave this issue open because it doesn't meet our contributing guidelines: https://github.com/DavyJonesLocker/client_side_validations-simple_form/blob/master/CONTRIBUTING.md

Please edit the first post, adding all the missing information and ping me

Meanwhile, closing here
